name: Build MTR Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          ./gradlew setupFiles -PminecraftVersion="1.21.1"
          ./gradlew build -PminecraftVersion="1.21.1"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MTR-Mod
          path: build/release/mtr_1.21.1.jar
