name: Bug Report
description: Help improve the MTR Mod by report bugs!
labels: [ "bug" ]
body:
    -   type: checkboxes
        attributes:
            label: Before reporting, I have confirmed that
            options:
            - label: This bug does not appear to be reported in the [Issues page](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
              required: true
            - label: This bug still exist in the latest version of the MTR Mod.
              required: true
            - label: I have tested this in the official version of MTR, not a modified/custom/unofficial build.
              required: true
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: |
                A clear and concise description of what the bug is, and what are you expecting instead.  
                You may use screenshot or videos to demonstrate the bug **in addition to your description.**
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Please list the steps needed in order to recreate your bug.
            value: |
                1.
                2.
                3.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: In-game Log/Crash Report
            description: |
                In-game logs can be very useful to determine the causes of the bug.  
                Whenever applicable, you should upload the in-game log here. It can be found in `.minecraft/logs/latest.log`.  
                If the game have crashed, you should also upload the crash report here, located in the `.minecraft/crash-reports` folder.
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Mod Loader
            description: Which modloader were you using when you encountered the bug?
            options:
                - "Fabric"
                - "Minecraft Forge"
        validations:
            required: true
    -   type: input
        attributes:
            label: Minecraft Version
            description: Which Minecraft version you were using when you encountered the bug? (e.g. 1.20.4)
            placeholder: "1.20.4"
        validations:
            required: true
    -   type: input
        attributes:
            label: MTR Version
            description: What version of MTR Mod were you using when you encountered the bug?
            placeholder: "4.0.0"
        validations:
            required: true
    -   type: input
        attributes:
            label: Operating System
            description: Please specify the operating system you are using that can re-create the bug (e.g. Windows 11, macOS Sonoma, Debian 12)
            placeholder: Windows 11
        validations:
            required: true
    -   type: textarea
        attributes:
            label: List of mods/modpack you were using
            description: |
                Please fill in the list the mods you were using when the bug occurred. (e.g. Screenshot of the mod folder or a full list of mods in plain text)  
                If you are using a modpack, it might be preferable to fill in the Modpack name/link, along with any other additional mods you were using.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Extra Informations
            description: If you have any insights or noticed any other odd behaviors that may be causing this, please fill in here.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: Thanks for reporting! Note that further enquiries may be made on this issue if necessary to identify the issue.
